name: sparta
description: Sparta
version: 0.0.19

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.4"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_redux: ^0.10.0
  http: ^0.13.5
  intl: ^0.17.0
  redux_epics: ^0.15.1
  shared_preferences: ^2.0.15

dev_dependencies:
  dart_code_metrics: ^4.19.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ">=3.1.0 <5.0.0"

flutter:
  assets:
    - google_fonts/
  fonts:
    - family: OpenSans
      fonts:
        - asset: google_fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: google_fonts/OpenSans-Regular.ttf
          weight: 400
  generate: true
  uses-material-design: true
