name: sparta
description: Sparta
version: 0.0.11

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.3"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_redux: ^0.10.0
  http: ^0.13.4
  intl: ^0.17.0
  redux: ^5.0.0
  redux_epics: ^0.15.1
  redux_logging: ^0.5.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1

flutter:
  assets:
    - google_fonts/
  fonts:
    - family: OpenSans
      fonts:
        - asset: google_fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: google_fonts/OpenSans-Regular.ttf
          weight: 400
  generate: true
  uses-material-design: true
