name: sparta
description: Sparta
version: 0.0.9

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.3
  flutter_redux: ^0.9.0
  http: ^0.13.4
  intl: ^0.17.0
  redux_epics: ^0.15.1
  redux_logging: ^0.5.0
  shared_preferences: ^2.0.13

dev_dependencies:
  akaiser_flutter_lints:
    git: https://github.com/akaiser/akaiser_flutter_lints.git
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - google_fonts/
  fonts:
    - family: OpenSans
      fonts:
        - asset: google_fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: google_fonts/OpenSans-Regular.ttf
          weight: 400
  generate: true
  uses-material-design: true
