name: Release macOS
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.2'
          channel: 'stable'
          architecture: arm64
      - name: Build
        run: flutter build macos
      - name: Release to Github
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/macos/Build/Products/Release/sparta.app"
          token: ${{ secrets.GITHUB_TOKEN }}
