name: Test
on:
  push:
    branches-ignore:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.2'
          channel: 'stable'
      - run: flutter analyze
      - run: flutter format -n --set-exit-if-changed .
      - run: flutter test
      - run: |
          flutter config --enable-linux-desktop
          flutter test -d linux integration_test
