name: Test
on:
  push:
    branches-ignore:
      - main
jobs:
  test:
    runs-on: macos-latest #TODO(albert) switch back to linux
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.2'
          channel: 'stable'
      - run: flutter analyze
      - run: flutter format -n --set-exit-if-changed .
      - run: flutter test
      - run: flutter test integration_test -d linux
